export const appData = [
  {
    id: 1,
    name: "tree leaf",
    email: "treeleaf@gmail.com",
    phoneNumber: "0987654",
    dob: "29/03/2000",
    city: "kathmandu",
    district: "kathmandu",
    province: "bagmati",
    country: "nepal",
  },
  {
    id: 2,
    name: "tree ",
    email: "treel@gmail.com",
    phoneNumber: "0987654",
    dob: "29/03/2000",
    city: "kathmandu",
    district: "kathmandu",
    province: "bagmati",
    country: "nepal",
  },
  {
    id: 3,
    name: " leaf",
    email: "leaf@gmail.com",
    phoneNumber: "0987654",
    dob: "29/03/2000",
    city: "kathmandu",
    district: "kathmandu",
    province: "bagmati",
    country: "nepal",
  },
];
